<?php
define('LARGE_DATA_FILE', 'Large data file. Unable to restore it. Please contact your system administrator. <br>or, Try with another one.<br><br>');




$ignore_table = array(
    'eimbox',
    'accesslevel',
    'accounts',
    'adminnotes',
    'amountrequest',
    'audit_temp',
    'backup_info',
    'backup_module',
    'biotree',
    'blood',
    'browser',
    'clublist',
    'datatest',
    'error_scanner',
    'examname',
    'filelist',
    'georecord',
    'globalsettings',
    'gpa',
    'indivisualrecord',
    'inoutdata',
    'inoutdate',
    'issue',
    'kbase1',
    'kbase2',
    'kbase3',
    'kbase4',
    'kbasedone',
    'kbasestep',
    'leaveapp',
    'links', 'loader',
    'lottery',
    'meritlist',
    'msgsupport',
    'notice_category',
    'notification',
    'orders',
    'otp',
    'payscale',
    'pibiarea',
    'pibientry',
    'pibigroup',
    'pibiprocess',
    'pibiskill',
    'pibitopics',
    'profile_track',
    'proxylist',
    'qrcodelogin',
    'salery',
    'salerypay',
    'scinfo',
    'se',
    'services',
    'settings',
    'slots',
    'smschairman',
    'studentfinancesetting',
    'subjectlist',
    'subscription',
    'tabulatingsheetpibi',
    'taka',
    'transaction_details',
    'tsalery',
    'userlog',
    'users',
    'usersapp',
    'user_level',
    'whatsnew'
);